### PR TITLE
-Modified to handle local variable for threading

### PR DESCRIPTION
**Pull request by milanac030988**
*Fixed issue https://github.com/test-fullautomation/robotframework/issues/50

### CODE REVIEW

**Comment by test-fullautomation** [comment]
Hi @milanac030988 ,
very good!
Can you please also activate the corresponding selftest (I think I implemented this already?) and maintain the release_info file?
Thank you,
 Thomas

**Comment by HolQue** [comment]
Hi Cuong,

you can activate additional tests (= additional test folders) in the TestTrigger configuration file in this way:

`"LOCALCOMMANDLINE"  : ["-d \"./atest/aiotestlogfiles\"", "-b aiotestlogfile.log", "-o aiotestlogfile.xml", "\"./atest/robot/log_level\"", "\"./atest/robot/additional_test\""],
`
(additional path in the list)

**Comment by test-fullautomation** [comment]
Hi Cuong,
what Holger writes is also good. We would then have the threading selftest in our dashboard.
But what I meant is to activate the tests withing the threading.robot file which I commented out due to issues.
Thank you,
 Thomas

**Comment by milanac030988** [comment]
Hello Thomas (@test-fullautomation ),

To avoid create too many branch for threding bugs fixing. I created a new branch ugc1hc/feat/develop_6.1_threading_stabilization and then merge all fixed bugs to this branch. 
At the end, I'll request a pull request from ugc1hc/feat/develop_6.1_threading_stabilization to develop_6.1 branch.

Thanks,
Cuong

**Comment by test-fullautomation** [comment]
Hi @milanac030988 ,
uups, I overlooked the branch message.
Goal was according to our branching strategy for future comunity pull-requests, that all thread releated changes are at one branch (ugc1hc/feat/threading_feature).
Can you please bring this change as well as https://github.com/test-fullautomation/robotframework/pull/73
to (ugc1hc/feat/threading_feature), and create a new pull-request?
Thank you,
 Thomas

**Comment by milanac030988** [comment]
> Hi @milanac030988 , uups, I overlooked the branch message. Goal was according to our branching strategy for future comunity pull-requests, that all thread releated changes are at one branch (ugc1hc/feat/threading_feature). Can you please bring this change as well as #73 to (ugc1hc/feat/threading_feature), and create a new pull-request? Thank you, Thomas

Hi Thomas,
I've merge to  (ugc1hc/feat/threading_feature) and create pull request https://github.com/test-fullautomation/robotframework/pull/75
Thanks,
Cuong

**Comment by test-fullautomation** [comment]
very good!

**Pull request merged**
