### PR TITLE
Ugc1hc/feat/threading feature

### PR DESCRIPTION
**Pull request by milanac030988**
*Fixed issues:
https://github.com/test-fullautomation/robotframework/issues/48
https://github.com/test-fullautomation/robotframework/issues/45
https://github.com/test-fullautomation/robotframework/issues/43
https://github.com/test-fullautomation/robotframework/issues/42
https://github.com/test-fullautomation/robotframework/issues/41
https://github.com/test-fullautomation/robotframework/issues/50
https://github.com/test-fullautomation/robotframework/issues/46
https://github.com/test-fullautomation/robotframework/issues/49

### CODE REVIEW

**Review by HolQue — COMMENTED** [review]
Hi Cuong,

w.r.t. threading documentation: Some aspects are not yet clear to me.

**(1)**

You mentioned the thread syntax:

`THREAD    ${ThreadName}    ${IsDaemon}`

But where to place thread definitions? Under "`*** Keywords ***`"?

**(2)**

You describe how to define threads and how to handle notifications.

But how to start a thread?

**(3)**

Let's say a user defined keyword increments a counter. What will happen if several threads call this keyword in parallel? Will the scopes be separated? Any recommendations for users?

**(4)**

You mention the thread name: "_It’s used for identification and logging purposes. The thread name should be unique within the context of the test suite to avoid confusion._"

You use the term '_should_', and not '_must_'. Is my understanding right that unique thread names are a recommendation only, but not a strict syntax requirement? I would agree in case of the thread name would only be a string written to log file, nothing else. But in the description of keyword `Send Thread Notification` you mention a `dst_thread`. Is this the same name like the `${ThreadName}` you use in the threading syntax description?

If this thread name is the connective link between the thread definition and the thread notification, I would say keeping thread names unique is not a '_should_' any more, but a '_must_'. Is it possible to check this? At least to give a warning in case of ambiguous thread names are detected?

**(5)**

In case of the thread is really a name only, I would assume that spelling doesn't matter. But if the name is used as '`dst_thread`' parameter, does the spelling have to be case sensitive or not?

I would be helpful you add some explanations to give more clarify about the topics above.

**Comment by milanac030988** [comment]
Hello Holger,

I'd like to answer your questions regarding to threading document:

1. The THREAD works as a keyword like FOR, WHILE or TRY, you can call it in a testcase or put it in a User Defined keyword.
2. The THREAD start as soon as it call, it mean after the line 'THREAD    ${ThreadName}    ${IsDaemon}'
3. Different threads has different variables scopes.
4. I don't want to restrict users from naming threads with duplicate names, even though it's generally not advisable due to the potential for overlapping log files and receiving notifications from other threads, leading to strange behaviors. I prefer to give users more freedom and hold them more accountable for the scripts they write. In certain situations, this flexibility could serve their specific purposes. For example, they might want to send notifications to two specific threads instead of broadcasting to all or just one. Therefore, allowing duplicate thread names could be beneficial in these unique scenarios, despite the inherent risks.
5. It's case sensitive 

Thanks,
Cuong

**Comment by test-fullautomation** [comment]
Hi Holger,
I agree to Cuong's answer.
Thank you,
 Thomas

**Review by test-fullautomation — APPROVED** [review]
Hi Cuong,
very good!
Thank you,
 Thomas

**Pull request merged**
